# Appium自动化测试框架配置文件

# Appium服务配置
appium:
  host: "127.0.0.1"
  port: 4723
  command_timeout: 60
  new_command_timeout: 300

# Android设备配置
android:
  platform_name: "Android"
  platform_version: "13"  # 根据实际设备版本修改
  device_name: "Android Device"
  automation_name: "UiAutomator2"
  app_activity: ""  # 应用的主Activity
  app_package: ""   # 应用包名
  app_path: ""      # APK文件路径（可选）
  no_reset: true
  full_reset: false
  unicode_keyboard: true
  reset_keyboard: true

# iOS设备配置
ios:
  platform_name: "iOS"
  platform_version: "16.0"  # 根据实际设备版本修改
  device_name: "iPhone"
  automation_name: "XCUITest"
  bundle_id: ""      # 应用Bundle ID
  app_path: ""       # IPA文件路径（可选）
  no_reset: true
  full_reset: false
  udid: ""           # 设备UDID

# 测试配置
test:
  implicit_wait: 10
  explicit_wait: 30
  page_load_timeout: 30
  screenshot_on_failure: true
  retry_count: 2

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_handler: true
  console_handler: true

# 报告配置
report:
  allure_results_dir: "reports/allure-results"
  html_report_dir: "reports/html"
  screenshots_dir: "reports/screenshots"

# 数据配置
data:
  test_data_dir: "data"
  excel_file: "test_data.xlsx"
  json_file: "test_data.json"